name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Integración Continua
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Verificar existencia de home.html
        run: |
          if [ -f "pages/home.html" ]; then
            echo "✅ home.html existe"
          else
            echo "❌ home.html no existe"
            exit 1
          fi

      - name: Verificar existencia de styles.css
        run: |
          if [ -f "styles.css" ]; then
            echo "✅ styles.css existe"
          else
            echo "❌ styles.css no existe"
            exit 1
          fi

  cd:
    name: Despliegue Continuo
    runs-on: ubuntu-latest
    needs: ci
    enviroment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url} }

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Simulación de despliegue
        id: deployment
        uses: actions/deploy-pages@v4
        run: echo "Artefactos listos para el despliegue en el entorno de Staging"

